package View.Kasir;


import View.Kasir.*;
import Controller.BarangDAO;
import Controller.DetailBarangDAO;
import Controller.DetailBarangService;
import Controller.PembelianDAO;
import Controller.PembelianService;
import Etc.DatabaseConnection;
import Model.Barang;
import Model.DetailBarang;
import Model.Pembelian;
import View.LoginPanel;
import java.awt.Color;
import java.awt.Font;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ROG
 */
public class KelolaBarang extends javax.swing.JFrame {
    private Connection conn = DatabaseConnection.getConnection();
    private DefaultTableModel model = new DefaultTableModel();
    private BarangDAO barangDAO;
    private DetailBarangDAO detailBarangDAO;
    private PembelianDAO pembelianDAO;
    private DetailBarangService detailBarangService;
    private PembelianService pembelianService;
    
    /**
     * Creates new form KelolaBarang
     */
    public KelolaBarang() {
        initComponents();
        if (conn == null) {
        JOptionPane.showMessageDialog(null, "Gagal terhubung ke database.");
        } else {
            barangDAO = new BarangDAO(conn);
            detailBarangDAO = new DetailBarangDAO(conn);
            pembelianDAO = new PembelianDAO(conn);
            detailBarangService = new DetailBarangService(conn);
            pembelianService = new PembelianService(detailBarangDAO);
        }
        model.addColumn("No.");
        model.addColumn("Kode");
        model.addColumn("Nama Barang");
        model.addColumn("Qty");
        model.addColumn("Harga Beli");
        model.addColumn("Harga Jual");
        model.addColumn("Profit");
        model.addColumn("ID Barang"); 
        model.addColumn("ID Detail Barang");
        model.addColumn("Tanggal Beli");
        model.addColumn("Keterangan");
        
        tableBarang.setModel(model);
        
        // Sembunyikan kolom "ID Barang"
        tableBarang.getColumnModel().getColumn(7).setMinWidth(0);
        tableBarang.getColumnModel().getColumn(7).setMaxWidth(0);
        tableBarang.getColumnModel().getColumn(7).setWidth(0);
        tableBarang.getColumnModel().getColumn(7).setPreferredWidth(0);
        
        // Sembunyikan kolom "ID Detail Barang"
        tableBarang.getColumnModel().getColumn(8).setMinWidth(0);
        tableBarang.getColumnModel().getColumn(8).setMaxWidth(0);
        tableBarang.getColumnModel().getColumn(8).setWidth(0);
        tableBarang.getColumnModel().getColumn(8).setPreferredWidth(0);
        
        // Sembunyikan kolom "Tanggal Beli"
        tableBarang.getColumnModel().getColumn(9).setMinWidth(0);
        tableBarang.getColumnModel().getColumn(9).setMaxWidth(0);
        tableBarang.getColumnModel().getColumn(9).setWidth(0);
        tableBarang.getColumnModel().getColumn(9).setPreferredWidth(0);
        
        // Sembunyikan kolom "Keterangan"
        tableBarang.getColumnModel().getColumn(10).setMinWidth(0);
        tableBarang.getColumnModel().getColumn(10).setMaxWidth(0);
        tableBarang.getColumnModel().getColumn(10).setWidth(0);
        tableBarang.getColumnModel().getColumn(10).setPreferredWidth(0);
        
        setLocationRelativeTo(null);
        
        
        loadData();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        tabelBarangLbl = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        namaBarangTxt = new javax.swing.JTextField();
        tambahBarangBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableBarang = new javax.swing.JTable();
        buatKodeBarangTxt = new javax.swing.JTextField();
        ubahBarangBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        transaksiBarangTxt = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        beliNamaBarangTxt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        beliHargaBeliTxt = new javax.swing.JTextField();
        beliQtyTxt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        beliHargaJualTxt = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        beliKodeBarang = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        keteranganTextBox = new javax.swing.JTextArea();
        beliTanggalBeliChooser = new com.toedter.calendar.JDateChooser();
        jLabel15 = new javax.swing.JLabel();
        prosesBeliBarang = new javax.swing.JButton();
        ubahBarang = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel19 = new javax.swing.JLabel();
        salesBtn5 = new javax.swing.JButton();
        kelolaBarangBtn = new javax.swing.JButton();
        pemutihanBtn = new javax.swing.JButton();
        logoutBtn5 = new javax.swing.JButton();
        laporanBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tabelBarangLbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tabelBarangLbl.setText("Tabel Barang");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Kode Barang:");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setText("Nama Barang:");

        namaBarangTxt.setText("Masukkan Nama Barang");
        namaBarangTxt.setToolTipText("");
        namaBarangTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                namaBarangTxtFocusGained(evt);
            }
        });

        tambahBarangBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tambahBarangBtn.setText("Tambah");
        tambahBarangBtn.setAlignmentY(0.0F);
        tambahBarangBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tambahBarangBtnMouseClicked(evt);
            }
        });

        tableBarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "No.", "Kode", "Nama Barang", "Qty", "Harga Beli", "Harga Jual", "Profit", "ID Barang", "ID Pembelian"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableBarang.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tableBarang.setShowGrid(true);
        tableBarang.getTableHeader().setReorderingAllowed(false);
        tableBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableBarangMouseClicked(evt);
            }
        });
        tableBarang.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tableBarangPropertyChange(evt);
            }
        });
        jScrollPane1.setViewportView(tableBarang);
        if (tableBarang.getColumnModel().getColumnCount() > 0) {
            tableBarang.getColumnModel().getColumn(0).setPreferredWidth(30);
            tableBarang.getColumnModel().getColumn(0).setMaxWidth(30);
            tableBarang.getColumnModel().getColumn(1).setPreferredWidth(80);
            tableBarang.getColumnModel().getColumn(1).setMaxWidth(80);
            tableBarang.getColumnModel().getColumn(2).setPreferredWidth(150);
            tableBarang.getColumnModel().getColumn(3).setPreferredWidth(30);
            tableBarang.getColumnModel().getColumn(3).setMaxWidth(30);
            tableBarang.getColumnModel().getColumn(4).setPreferredWidth(80);
            tableBarang.getColumnModel().getColumn(4).setMaxWidth(80);
            tableBarang.getColumnModel().getColumn(5).setPreferredWidth(80);
            tableBarang.getColumnModel().getColumn(5).setMaxWidth(80);
            tableBarang.getColumnModel().getColumn(6).setPreferredWidth(80);
            tableBarang.getColumnModel().getColumn(6).setMaxWidth(80);
            tableBarang.getColumnModel().getColumn(7).setResizable(false);
            tableBarang.getColumnModel().getColumn(7).setPreferredWidth(0);
            tableBarang.getColumnModel().getColumn(8).setPreferredWidth(0);
        }

        buatKodeBarangTxt.setText("Buat Kode Barang");
        buatKodeBarangTxt.setToolTipText("");
        buatKodeBarangTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                buatKodeBarangTxtFocusGained(evt);
            }
        });

        ubahBarangBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ubahBarangBtn.setText("Ubah");
        ubahBarangBtn.setAlignmentY(0.0F);
        ubahBarangBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ubahBarangBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tabelBarangLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buatKodeBarangTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(7, 7, 7)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(0, 456, Short.MAX_VALUE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(namaBarangTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tambahBarangBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ubahBarangBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(tabelBarangLbl)
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buatKodeBarangTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ubahBarangBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tambahBarangBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(namaBarangTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 439, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        transaksiBarangTxt.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        transaksiBarangTxt.setText("Transaksi Pembelian Barang");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Kode Barang:");

        beliNamaBarangTxt.setToolTipText("");
        beliNamaBarangTxt.setEnabled(false);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Nama Barang:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Harga Beli:");

        beliHargaBeliTxt.setToolTipText("");

        beliQtyTxt.setToolTipText("");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Qty:");

        beliHargaJualTxt.setToolTipText("");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setText("Harga Jual:");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setText("Keterangan:");

        beliKodeBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beliKodeBarangActionPerformed(evt);
            }
        });

        keteranganTextBox.setColumns(20);
        keteranganTextBox.setRows(5);
        keteranganTextBox.setText("Tulis Keterangan");
        keteranganTextBox.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                keteranganTextBoxFocusGained(evt);
            }
        });
        jScrollPane2.setViewportView(keteranganTextBox);

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setText("Tanggal Beli:");

        prosesBeliBarang.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        prosesBeliBarang.setText("Proses");
        prosesBeliBarang.setAlignmentY(0.0F);
        prosesBeliBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                prosesBeliBarangMouseClicked(evt);
            }
        });

        ubahBarang.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ubahBarang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Edit.png"))); // NOI18N
        ubahBarang.setText("Ubah");
        ubahBarang.setAlignmentY(0.0F);
        ubahBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ubahBarangMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(beliHargaBeliTxt)
                    .addComponent(beliNamaBarangTxt, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(beliHargaJualTxt, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(beliQtyTxt, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(prosesBeliBarang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ubahBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(transaksiBarangTxt, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(beliKodeBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel15)
                                    .addComponent(beliTanggalBeliChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(transaksiBarangTxt)
                .addGap(13, 13, 13)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(beliTanggalBeliChooser, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(beliKodeBarang))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(beliNamaBarangTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addGap(13, 13, 13)
                .addComponent(beliQtyTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(beliHargaBeliTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(beliHargaJualTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prosesBeliBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ubahBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel10.setBackground(new java.awt.Color(102, 153, 255));

        jLabel17.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Selamat datang,");

        jLabel19.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Kasir");

        salesBtn5.setText("Penjualan");
        salesBtn5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salesBtn5MouseClicked(evt);
            }
        });

        kelolaBarangBtn.setText("Kelola Barang");
        kelolaBarangBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kelolaBarangBtnMouseClicked(evt);
            }
        });

        pemutihanBtn.setText("Pemutihan Barang");
        pemutihanBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pemutihanBtnMouseClicked(evt);
            }
        });

        logoutBtn5.setText("Logout");
        logoutBtn5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutBtn5MouseClicked(evt);
            }
        });

        laporanBtn.setText("Laporan");
        laporanBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                laporanBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66)
                .addComponent(salesBtn5, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(kelolaBarangBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pemutihanBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(laporanBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logoutBtn5)
                .addGap(34, 34, 34))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel19))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(salesBtn5)
                            .addComponent(kelolaBarangBtn)
                            .addComponent(pemutihanBtn)
                            .addComponent(logoutBtn5)
                            .addComponent(laporanBtn))))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public void loadData() {
        beliKodeBarang.removeAllItems();
        beliKodeBarang.addItem("Pilih Kode Barang");
        for(Barang kdBrg : barangDAO.getAll()) {
            beliKodeBarang.addItem(kdBrg.getKodeBarang());
        }
        // Kosongkan tabel
        model.setRowCount(0);
        
        barangDAO = new BarangDAO(conn);
        detailBarangDAO = new DetailBarangDAO(conn);
        
        List<DetailBarang> allBarang = detailBarangDAO.getAll();
        int i = 1;
        for(DetailBarang barang : allBarang) {
            model.addRow(new Object[] {
                i,
                barang.getBarang().getKodeBarang(),
                barang.getBarang().getNamaBarang(),
                barang.getQty(),
                barang.getHargaBeli(),
                barang.getHargaJual(),
                barang.getProfit(),
                barang.getBarang().getBarangId(),
                barang.getDetailBarangId(),
                barang.getTanggalBeli(),
                barang.getKeterangan(),
            });
            i++;
        }
    }
    
    public void addPlaceHolderStyle(JTextField textField) {
        Font font = textField.getFont();
        font = font.deriveFont(Font.ITALIC);
        textField.setFont(font);
        textField.setForeground(Color.gray);
    }
    
    public void removePlaceHolderStyle(JTextField textField) {
        Font font = textField.getFont();
        font = font.deriveFont(Font.PLAIN|Font.BOLD);
        textField.setFont(font);
        textField.setForeground(Color.black);
    }
    
    public void addPlaceHolderStyle(JTextArea TextArea) {
        Font font = TextArea.getFont();
        font = font.deriveFont(Font.ITALIC);
        TextArea.setFont(font);
        TextArea.setForeground(Color.gray);
    }
    
    public void removePlaceHolderStyle(JTextArea TextArea) {
        Font font = TextArea.getFont();
        font = font.deriveFont(Font.PLAIN|Font.BOLD);
        TextArea.setFont(font);
        TextArea.setForeground(Color.black);
    }
    
    private void buatKodeBarangTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_buatKodeBarangTxtFocusGained
        if(buatKodeBarangTxt.getText().equals("Buat Kode Barang")) {
            buatKodeBarangTxt.setText(null);
            buatKodeBarangTxt.requestFocus();
            // Remove placeholder style
            removePlaceHolderStyle(buatKodeBarangTxt);
        }
    }//GEN-LAST:event_buatKodeBarangTxtFocusGained

    private void namaBarangTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_namaBarangTxtFocusGained
        if(namaBarangTxt.getText().equals("Masukkan Nama Barang")) {
            namaBarangTxt.setText(null);
            namaBarangTxt.requestFocus();
            // Remove placeholder style
            removePlaceHolderStyle(namaBarangTxt);
        }
    }//GEN-LAST:event_namaBarangTxtFocusGained

    private void keteranganTextBoxFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_keteranganTextBoxFocusGained
        if(keteranganTextBox.getText().equals("Tulis Keterangan")) {
            keteranganTextBox.setText(null);
            keteranganTextBox.requestFocus();
            // Remove placeholder style
            removePlaceHolderStyle(keteranganTextBox);
        }
    }//GEN-LAST:event_keteranganTextBoxFocusGained

    private void tambahBarangBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tambahBarangBtnMouseClicked
        String kode_barang = buatKodeBarangTxt.getText();
        String nama_barang = namaBarangTxt.getText();
        
        if(!kode_barang.isEmpty() || !nama_barang.isEmpty()) {
            Barang brg = new Barang(kode_barang, nama_barang);

            barangDAO.insert(brg);
            try {
                Thread.sleep(500);
            } catch (InterruptedException ex) {
                Logger.getLogger(KelolaBarang.class.getName()).log(Level.SEVERE, null, ex);
            }
            loadData();
        } else {
            JOptionPane.showMessageDialog(null, "Harap memasukkan kode dan nama barang", "Input Error", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_tambahBarangBtnMouseClicked

    private void tableBarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableBarangMouseClicked
        try {
            int selectedRow = tableBarang.getSelectedRow();
            if (selectedRow != -1) {
                Object kodeBarang = model.getValueAt(selectedRow, 1);
                Object namaBarang = model.getValueAt(selectedRow, 2);
                Object qty = model.getValueAt(selectedRow, 3);
                Object hargaBeli = model.getValueAt(selectedRow, 4);
                Object hargaJual = model.getValueAt(selectedRow, 5);
                Date tanggal_beli = (Date) model.getValueAt(selectedRow, 9);
                Object keterangan = model.getValueAt(selectedRow, 10);
                
                buatKodeBarangTxt.setText(kodeBarang != null ? kodeBarang.toString() : "");
                namaBarangTxt.setText(namaBarang != null ? namaBarang.toString() : "");
                beliKodeBarang.setSelectedItem(kodeBarang != null ? kodeBarang.toString() : "");
                beliNamaBarangTxt.setText(namaBarang != null ? namaBarang.toString() : "");
                beliQtyTxt.setText(qty != null ? qty.toString() : "");
                beliHargaBeliTxt.setText(hargaBeli != null ? hargaBeli.toString() : "");
                beliHargaJualTxt.setText(hargaJual != null ? hargaJual.toString() : "");
                beliTanggalBeliChooser.setDate(tanggal_beli != null ? tanggal_beli : null);
                keteranganTextBox.setText(keterangan != null ? keterangan.toString() : "");
            } else {
                JOptionPane.showMessageDialog(null, "Tidak ada baris yang dipilih.");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_tableBarangMouseClicked

    private void prosesBeliBarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prosesBeliBarangMouseClicked
        int selectedRow = tableBarang.getSelectedRow();
        if (selectedRow != -1) {
            int barang_id = Integer.parseInt(model.getValueAt(selectedRow, 7).toString());
            String kode_barang = buatKodeBarangTxt.getText();
            String nama_barang = namaBarangTxt.getText();
            Date tanggal_beli = beliTanggalBeliChooser.getDate();
            int qty = Integer.parseInt(beliQtyTxt.getText());
            double harga_beli = Double.parseDouble(beliHargaBeliTxt.getText());
            double harga_jual = Double.parseDouble(beliHargaJualTxt.getText());
            double profit = harga_jual - harga_beli;
            String keterangan = keteranganTextBox.getText();
            
            if(!kode_barang.isEmpty() && !nama_barang.isEmpty() && tanggal_beli != null && qty > 0 && 
                harga_beli != 0 && harga_jual != 0) {
                Barang brg = new Barang(barang_id, kode_barang, nama_barang);
                Pembelian pbl = new Pembelian(barang_id, tanggal_beli, brg, qty, harga_beli, harga_jual, 
                        profit, keterangan);
                
                try {
                    // Proses detail barang: update atau insert
                    pembelianService.processIncomingStock(pbl);
                    
                    // Simpan transaksi pembelian
                    pembelianDAO.insert(pbl);
                    
                    Thread.sleep(500);
                    
                    loadData();
                } catch (SQLException ex) {
                    Logger.getLogger(KelolaBarang.class.getName()).log(Level.SEVERE, null, ex);
                } catch (InterruptedException ex) {
                    Logger.getLogger(KelolaBarang.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Harap memasukkan data secara lengkap", "Input Error", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Tidak ada baris yang dipilih.");
        }
    }//GEN-LAST:event_prosesBeliBarangMouseClicked

    private void ubahBarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ubahBarangMouseClicked
        int selectedRow = tableBarang.getSelectedRow();
        if (selectedRow != -1) {
            int barang_id = Integer.parseInt(model.getValueAt(selectedRow, 7).toString());
            int detail_barang_id = Integer.parseInt(model.getValueAt(selectedRow, 8).toString());
            String kode_barang = buatKodeBarangTxt.getText();
            String nama_barang = namaBarangTxt.getText();
            Date tanggal_beli = beliTanggalBeliChooser.getDate();
            int qty = Integer.parseInt(beliQtyTxt.getText());
            double harga_beli = Double.parseDouble(beliHargaBeliTxt.getText());
            double harga_jual = Double.parseDouble(beliHargaJualTxt.getText());
            double profit = harga_jual - harga_beli;
            String keterangan = keteranganTextBox.getText();
            
            if(!kode_barang.isEmpty() && !nama_barang.isEmpty() && tanggal_beli != null && qty >= 0 && 
                harga_beli != 0 && harga_jual != 0) {
                Barang brg = new Barang(barang_id, kode_barang, nama_barang);
                DetailBarang detailBarang = new DetailBarang(detail_barang_id, brg, qty, harga_beli, harga_jual, 
                    profit, tanggal_beli, keterangan);
                
                detailBarangService.updateDataBarangDanDetail(detailBarang);
                loadData();
            } else {
                JOptionPane.showMessageDialog(null, "Harap memasukkan data secara lengkap", "Input Error", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Tidak ada baris yang dipilih.");
        }
    }//GEN-LAST:event_ubahBarangMouseClicked

    private void ubahBarangBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ubahBarangBtnMouseClicked
        int selectedRow = tableBarang.getSelectedRow();
        if (selectedRow != -1) {
            int barang_id = (int) model.getValueAt(selectedRow, 7);
            String kode_barang = buatKodeBarangTxt.getText();
            String nama_barang = namaBarangTxt.getText();

            Barang brg = new Barang(barang_id, kode_barang, nama_barang);

            barangDAO.update(brg);
            try {
                Thread.sleep(500);
            } catch (InterruptedException ex) {
                Logger.getLogger(KelolaBarang.class.getName()).log(Level.SEVERE, null, ex);
            }
            loadData();
        } else {
            JOptionPane.showMessageDialog(null, "Tidak ada baris yang dipilih.");
        }
    }//GEN-LAST:event_ubahBarangBtnMouseClicked

    private void beliKodeBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beliKodeBarangActionPerformed
        Object selectedItem = beliKodeBarang.getSelectedItem();

        if (selectedItem == null) {
            // Jika belum ada item dipilih, reset field
            beliNamaBarangTxt.setText("");
            tableBarang.clearSelection();
            return;
        }
        
        String kode_barang = selectedItem.toString().trim();
        
        if(!kode_barang.equals("Pilih Kode Barang")) {
            Barang barang = barangDAO.getByKdBarang(kode_barang);
            if(barang != null) {
                beliNamaBarangTxt.setText(barang.getNamaBarang());
                
                for (int i = 0; i < model.getRowCount(); i++) {
                    String kodeBarangTabel = model.getValueAt(i, 1).toString(); // Kolom kode_barang di tabel
                    if (kodeBarangTabel.equals(kode_barang)) {
                        tableBarang.setRowSelectionInterval(i, i); // Pilih baris pertama yang cocok
                        break;
                    }
                }
            } else {
                JOptionPane.showMessageDialog(null, "Kode barang tidak ditemukan di database.");
                beliNamaBarangTxt.setText("");
                tableBarang.clearSelection();
            }
        } else {
            beliNamaBarangTxt.setText("");
            tableBarang.clearSelection();
        }
    }//GEN-LAST:event_beliKodeBarangActionPerformed

    private void salesBtn5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salesBtn5MouseClicked
        Penjualan penjualanPage = new Penjualan();
        penjualanPage.setVisible(true);
        penjualanPage.setLocationRelativeTo(null);

        this.setVisible(false);
    }//GEN-LAST:event_salesBtn5MouseClicked

    private void kelolaBarangBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kelolaBarangBtnMouseClicked
        KelolaBarang kelolaBarangPage = new KelolaBarang();
        kelolaBarangPage.setVisible(true);
        kelolaBarangPage.setLocationRelativeTo(null);

        this.setVisible(false);
    }//GEN-LAST:event_kelolaBarangBtnMouseClicked

    private void pemutihanBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pemutihanBtnMouseClicked
        PemutihanBarang pemutihanPage = new PemutihanBarang();
        pemutihanPage.setVisible(true);
        pemutihanPage.setLocationRelativeTo(null);

        this.setVisible(false);
    }//GEN-LAST:event_pemutihanBtnMouseClicked

    private void logoutBtn5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutBtn5MouseClicked
        JOptionPane.showMessageDialog(null, "Anda berhasil keluar.");
        LoginPanel login = new LoginPanel();
        login.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_logoutBtn5MouseClicked

    private void tableBarangPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tableBarangPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_tableBarangPropertyChange

    private void laporanBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_laporanBtnMouseClicked
        Laporan laporanPage = new Laporan();
        laporanPage.setVisible(true);
        laporanPage.setLocationRelativeTo(null);

        this.setVisible(false);
    }//GEN-LAST:event_laporanBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KelolaBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KelolaBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KelolaBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KelolaBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KelolaBarang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField beliHargaBeliTxt;
    private javax.swing.JTextField beliHargaJualTxt;
    private javax.swing.JComboBox<String> beliKodeBarang;
    private javax.swing.JTextField beliNamaBarangTxt;
    private javax.swing.JTextField beliQtyTxt;
    private com.toedter.calendar.JDateChooser beliTanggalBeliChooser;
    private javax.swing.JTextField buatKodeBarangTxt;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton kelolaBarangBtn;
    private javax.swing.JTextArea keteranganTextBox;
    private javax.swing.JButton laporanBtn;
    private javax.swing.JButton logoutBtn5;
    private javax.swing.JTextField namaBarangTxt;
    private javax.swing.JButton pemutihanBtn;
    private javax.swing.JButton prosesBeliBarang;
    private javax.swing.JButton salesBtn5;
    private javax.swing.JLabel tabelBarangLbl;
    private javax.swing.JTable tableBarang;
    private javax.swing.JButton tambahBarangBtn;
    private javax.swing.JLabel transaksiBarangTxt;
    private javax.swing.JButton ubahBarang;
    private javax.swing.JButton ubahBarangBtn;
    // End of variables declaration//GEN-END:variables
}
